# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f8dcb0c6de8d34625a43c4d0c5b6f85967a8e902e67e261a6f3cef13be1b02c400f42447101cbe9b94816d7d8d7505dca64f0eb953ac580b90718afcd3ace141

test:
  secret_key_base: 67b0fa5d05899cc15f96a1b23d4bfdead3b7e951d040feb232691c189cdbe43bc680ff84bf7a00c2a9fbe0aea6fd150091831eb3e7015bba0385e1a6d5febebc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
